export const TOKENS = [
  "1INCH", "AAVE", "ACT", "ADA", "AEVO", "AGI", "AI16Z", "AIXBT", "AKRO", "AKT",
  "ALGO", "ALPHA", "ALT", "AMP", "ampKUJI", "ampLUNA", "ANC", "ANDR", "ANIME", "ANKR",
  "ANT", "ANY", "APE", "APOLLO", "APT", "AR", "ARB", "ARCH", "ASA", "ASTRO",
  "ATOM", "ATOM-dATOM", "AUDIO", "AUT", "AVA", "AVAIL", "AVAX", "AXL", "axlUSDC", "AXS",
  "AXT", "BAKE", "BAL", "BAND", "BAT", "BCD", "bCFX", "BCH", "BCHA", "BCN",
  "BCNA", "BELT", "BERA", "beraSTONE", "BETH", "BHC", "BIT", "BLAST", "BLD", "BLOX",
  "BLUR", "BNB", "bNEO", "BNT", "BOLT", "BONK", "BOOT", "BRAINS", "BRETT", "BRKL",
  "BTC", "BTCST", "BTG", "BTM", "BTMX", "BTSG", "BTT", "BUNNY", "BUSD", "BUSDT",
  "C98", "CAKE", "CANTO", "CARB", "CAT", "cbBTC", "cbETH", "CEL", "CELO", "CETH",
  "CFX", "CGAS", "CHEQ", "CHOG", "CHSB", "CHT", "CHZ", "CKB", "CMDX", "cmETH",
  "CMST", "CNT", "COIN", "COMP", "COOK", "CRBRUS", "CRE", "CRO", "CRV", "CTK",
  "cUSD", "CW", "DAG", "DAI", "DAK", "DARC", "DASH", "dATOM", "DBC", "DCR",
  "DEC", "DEGEN", "DENT", "DGB", "dGLP", "DIG", "dINJ", "DKT", "DODO", "DOGE",
  "DOT", "DPL", "DPX", "DRFT", "DROP", "DSM", "DUVT", "DVPN", "dXCAD", "DYDX",
  "DYM", "EEUR", "eGLD", "EGLD", "EIGEN", "ELA", "ELF", "ENA", "ENJ", "ENS",
  "EOS", "ePLAY", "EPS", "esFLUO", "ETC", "ETH", "ETHBTC", "ETN", "EUROC", "EUT",
  "EVMOS", "EWT", "FARTCOIN", "FBTC", "FEES", "FET", "FIL", "FIS", "FLIX", "FLM",
  "FLOW", "FLUID", "FLUO", "FRANK", "FSGLP", "FTM", "FTT", "FTTC", "FUN", "GALA",
  "GAMBIT", "GAS", "GBT", "GLP", "GM", "GMX", "GNO", "GNS", "GOAT", "GRASS",
  "GRAV", "GRT", "GT", "gZIL", "HBAR", "HDN", "HELMET", "HKT", "HNT", "HOPE",
  "HOT", "HT", "HUAHUA", "HUNY", "HUSD", "HYPE", "IBCX", "ICP", "ICX", "IDT",
  "INIT", "INJ", "INT", "ION", "IOST", "IOTX", "IOV", "IP", "IRIS", "iSEI",
  "iUSD", "IXO", "JPT", "JTO", "JUNO", "JUP", "KAITO", "KAS", "KBONK", "KCS",
  "KFLOKI", "KLAY", "KMD", "KNC", "KPEPE", "KRT", "KSHIB", "KSM", "KUJI", "LAYER",
  "LBTC", "LDO", "LEO", "LET", "LIKE", "LINK", "LKT", "LOOM", "LOOP", "LOTA",
  "LPT", "LRC", "LSI", "LSK", "LTC", "LUM", "LUNA", "LUNAX", "LUNC", "LUNI",
  "LUNR", "LUV", "LVN", "M87", "MANA", "MANTA", "MARBLE", "MATH", "MATIC", "MDX",
  "ME", "MED", "MEME", "mETH", "METIS", "MEW", "MIAW", "MILK", "milkTIA", "MINA",
  "MINE", "MIOTA", "MIR", "MKR", "MMOG", "MNT", "MNTA", "MNTL", "MON", "MOODENG",
  "MORPHO", "MYT", "NANO", "NAS", "NAT", "NEAR", "NEIROETH", "NEO", "NETA", "NEX",
  "NEXO", "NGM", "NIM", "NKN", "nLEND", "NMR", "nNEO", "NOT", "NOTE", "NTRN",
  "NTRN-dATOM", "NXM", "OCEAN", "OCH", "OGN", "OKB", "OKT", "OM", "OMG", "OMI",
  "OMNI", "ONDO", "ONE", "ONT", "OP", "OPUL", "ORDI", "ORION", "ORNE", "OSMO",
  "OXT", "OXY", "PAX", "PAXG", "PENDLE", "PENGU", "PEPE", "PHT", "PLAY", "PLQ",
  "PLY", "PNUT", "POL", "POLY", "POPCAT", "PORT", "PROM", "PSI", "PSTAKE", "PUDGY",
  "PUMP", "PUNDIX", "PURR", "PURSE", "PYTH", "QCK", "QKC", "QNT", "QTUM", "rATOM",
  "RAY", "RBN", "REEF", "REGEN", "REN", "REP", "REV", "RLB", "RLC", "RNDR",
  "ROAR", "ROWAN", "RSR", "rSWTH", "RUNE", "RVN", "S", "SAFEMOON", "SAGA", "SAND",
  "sARCH", "SAYVE", "SC", "SCRT", "SDT", "SEI", "SET", "SGT", "SHD", "SHIB",
  "SHIDO", "SITY", "SLERF", "SNT", "SNX", "SOL", "SOLETH", "SOM", "SOMM", "SPEC",
  "SRM", "SRV", "STARS", "stATOM", "stDYDX", "stDYM", "STEEM", "stETH", "stEVMOS",
  "stFLUO", "stIBCX", "stINJ", "stJUNO", "stkATOM", "stkDYDX", "stkSTARS", "stLUNA", "STMX",
  "stOKT", "STORJ", "stOSMO", "STRAX", "STRD", "STREAM", "STRK", "stSAGA", "stSTARS",
  "STT", "stTIA", "STX", "stZIL", "SUI", "SUN", "SUSHI", "SWTH", "SXP", "TAO",
  "TEL", "TFUEL", "THETA", "THT", "TIA", "TICK", "TITAN", "TLAND", "TLM", "TOMO",
  "TON", "TPC", "TRAXX", "TRB", "TRU", "TRUMP", "TRX", "TTT", "TUSD", "TWD",
  "TWT", "UBQ", "UMEE", "UNA", "UNI", "UOS", "USC", "USD", "USDC", "USDC-dATOM",
  "USDC.e", "USDC.grv", "USDP", "USDT", "USDY", "USK", "UST", "USUAL", "VDL",
  "veFLUO", "VET", "VIRTUAL", "VKR", "VRTX", "vZWAP", "W", "WAL", "WAVAX", "WAVE",
  "WBNB", "WBTC", "WETH", "WHALE", "WIF", "WIN", "wKAS", "WLD", "WMATIC", "WMNT",
  "WRX", "wstETH", "XCAD", "XDC", "XEM", "XKI", "XLM", "XMR", "XPRT", "XRP",
  "XSGD", "XTRA", "XTZ", "XVG", "XVS", "YAKI", "YAM", "YFI", "YieldUSD", "ZCH",
  "ZEC", "ZEN", "ZIL", "ZRO", "ZRX", "ZWAP"
]
